### ISSUE TITLE
0.6 roadmap (WIP)

### ISSUE THREAD

**Issue by Monniasza** [MultiMachineBuilder/MultiMachineBuilder#110]
- [x] #114
- [ ] BOM and crafting ingredient list generator
- add any suggestions or requests here
- [x] #111
- [x] #112
- [x] #113
- [x] https://github.com/MultiMachineBuilder/MultiMachineBuilder/issues/282
- [x] https://github.com/MultiMachineBuilder/MultiMachineBuilder/issues/279
- [x] https://github.com/MultiMachineBuilder/MultiMachineBuilder/issues/276
- [x] https://github.com/MultiMachineBuilder/MultiMachineBuilder/issues/275
- [x] Update wiki with new features
