### ISSUE TITLE
0.7 roadmap

### ISSUE THREAD

**Issue by Monniasza** [MultiMachineBuilder/MultiMachineBuilder#284]
- [ ] Remove deprecated items
- [ ] Massive refactoring
- [ ] Deprecate multiblock machines
- [ ] Release the 0.7 version
