### ISSUE TITLE
Modular and chassis blocks

### ISSUE THREAD

**Issue by Monniasza** [MultiMachineBuilder/MultiMachineBuilder#63]
A modular block is a block which accepts attachments (maybe restricted) and uses them.
A chassis block is similar, but also accepts cores (also can be restricted)
An attachment is a module or a core.
A block without attachments is also called an orchestrator.

The orchestrator communicates with attachments to achieve more flexibility than individual blocks alone

### Example: A chest
Inventory imlementations: 
- 4 types (multistack, set, stack, drawer)
- *9 sizes(6, 16, 32, 64, 256,  512, 1024, 4096, 16384)
- *6⁴ = 1296 extractor types(none, single, stack, multi, bulk, smart)^4
= 4 * 9 * 1296 = 46 656 (!!!)
That would overload the CPU and bore the user with loading times

Hard to upgrade:
Let's say that plugs be added
There would be lots of new types needed (now 7^5 extractors)

### A better solution:
- 4*9 = 36 core types (6, 16, 32, 64, 256,  512, 1024, 4096, 16384)×(multistack, set, stack, single)
- +5 extractor types (excl none)
- +1 chassis
= 42 types
Loading this is a breeze for modern PCs

Easier to upgrade:
Let's say that plugs be added
Just one new item needed.

### Design principle:
- Attachable to any block class. Using interfaces `ModularBlock`

### Tasks:
- [x] Create a chassis/modular/pluggable block
- [x] Create a chest configuration GUI
- [x] Create a chassis chest ("Super-Chest") (1)
- [x] Create drawer chest cores (9)
- [x] Create single item chest core (1)
- [x] Create set chest cores (9)
- [x] Create basic chest cores (9)
- [x] Test modular chests
- [ ] Commit changes
- [ ] Create a wiki page

### Create general purpose item attachments
- Plug - blocks access
- Single - one item at a time
- Stack - limited items
- Multi - multiple items
- Bulk - ensures integrity
- Filter - restricts items
- [x] Plug
- [x] Single Importer/Exporter
- [x] Multi Importer/Exporter
- [x] Bulk Importer/Exporter

Later:
- [ ] Filter
- [ ] Limiter
- [ ] Item specific detector
- [ ] All must be detector
- [ ] Inventory detector

### Logic attachments
- [ ] NOT signal in
- [ ] YES signal in
- [ ] NOT signal out
- [ ] YES signal in
